### ISSUE TITLE
Rename logger

### ISSUE THREAD

**Issue by MarkusH** [jneight/django-db-geventpool#18]
The loggers used in this project us the "django" name. This is not really helpful if one wants to filter for / out the geventpool events. It would be helpful to rename the logger either to `django.geventpool` or `geventpool`. The former could be propagated and managed by a parent "django" logger.

**Comment by jneight** [comment]
You are right, changed to 'django.geventpool'

Thanks

**Comment by MarkusH** [comment]
Thanks for fixing this @jneight :)
