### ISSUE TITLE
Docs for MAX_CONNS need clarification

### ISSUE THREAD

**Issue by DanielStevenLewis** [jneight/django-db-geventpool#21]
Upon first installing django-db-eventpool I set MAX_CONNS to be the same as the max_connections setting in PostgreSQL because that's what the readme seemed to indicate. 

After learning more about pooling and continuing to experience the issue that this library was supposed to resolve (i.e., https://github.com/benoitc/gunicorn/issues/996 ), I realized that MAX_CONNS is probably actually supposed to be the max connections _per pool_, so lowered the number dramatically. Could you please confirm this understanding and edit the readme accordingly if it's correct?

**Comment by hingston** [comment]
@DanielStevenLewis did you confirm that was the case? I'm wondering the same.

**Comment by DanielStevenLewis** [comment]
No, although I still think my explanation probably makes sense.

**Comment by jneight** [comment]
Sorry for the missing information at the docs and not being able to write before.

Due the way python and gevent works, the pool is shared between threads (or greenlets) inside the same python process, a connection can't be shared with other process. Remember that with gevent, one process can use hundred or thousand of connections at the same time, this pool allows to set a limit per process and also avoid django DB queries to block the process that will make gevent useless. If you want a global pool, pgbouncer or similar should be used.

So, MAX_CONNS should be set to (postgres's connections allowed / number of processes) or lower.

I'm no longer using gevent, so maybe something has changed at django side, the last version I has used this pool was 1.10.
