### ISSUE TITLE
psycopg2-binary requirement

### ISSUE THREAD

**Issue by mattbriancon** [jneight/django-db-geventpool#27]
I'm moving my app to use the new `psycopg2-binary` package [as recommended by the maintainers][1] but django-db-geventpool still requires `psycopg2`. 

I'd like to recommend either switching the `install_requires` to use `psycopg2-binary` or removing the requirement all together in favor of a runtime check (handling the `ImportError`). I'm happy to put together a PR, just want some input on the preferred direction.

[1]: http://initd.org/psycopg/articles/2018/02/08/psycopg-274-released/

**Comment by jneight** [comment]
Thanks for the info. I think that removing the requirement, adding a runtime check with a helpful text and a couple of lines at README should be OK, so anyone can use the psycopg2 package they need.

**Comment by tysonclugg** [comment]
The next release of psycopg2 may change the recommendation back to `psycopg2` instead of `psycopg2-binary`, as per https://github.com/psycopg/psycopg2/issues/719.

**Comment by mattbriancon** [comment]
Happy to hold off until a decision is made.

**Comment by joekohlsdorf** [comment]
Removing the requirement altogether as done in the PR is more useful.

**Comment by jneight** [comment]
Yes, I like to remove it from requirement, thanks for the PR!
