### ISSUE TITLE
Upgrade docs to show how to use with Celery workers

### ISSUE THREAD

**Issue by williamflynt** [jneight/django-db-geventpool#43]
The docs mention that connections don't close automatically in spawned greenlet workers that are not tied to a request cycle.

I'm trying to make my celery workers safe with the `@close_connections` decorator, but I don't know how (and I'm having trouble finding any docs mentioning worker customization).

I'm happy to submit a PR with an example, if someone can help me do it in the first place!

**Comment by jneight** [comment]
Hi!

Thanks, I'm going to update the README to make it clearer, but for now, this is the info you are looking for https://github.com/jneight/django-db-geventpool/blob/master/README.rst#using-django-16-orm-when-not-serving-requests
