### ISSUE TITLE
JSONField returns string with Django 2.2

### ISSUE THREAD

**Issue by fdemmer** [jneight/django-db-geventpool#53]
Since https://github.com/jneight/django-db-geventpool/pull/50 was merged all `JSONFields` return JSON as a `str` instead of `dict` with Django 2.2 (<3.0 actually, it also fails with Python 2.7 and Django 1.1). I updated the test to demonstrate the problem: https://github.com/fdemmer/django-db-geventpool/commit/73ea274ae4e2b106d5ae0ff374f848a2b0710032

Considering that Django 2.2 is LTS until April 2022, I'd recommend another 3.2.x release rolling back the change and a new 3.3.x or 4.x release with Django 3.x compatibility and documentation of the breaking change.

Would a PR with the updated test (and at least updated readme/changelog regarding compatibility) be welcome?

**Comment by jneight** [comment]
Hi!, that sounds great!, of course a PR is welcome :)
