### ISSUE TITLE
Django 2.2

### ISSUE THREAD

**Issue by salva-imm** [jneight/django-db-geventpool#59]
did you drop Django 2.2  (current stable and LTS version) ??
if no , then why you put django 3 on dependecies! it's removing my django (2.2) and installing 3.1

**Comment by jneight** [comment]
Django >= 3.1 has some changes in how JSONFields are handled that broke support to previous versions, https://github.com/jneight/django-db-geventpool/issues/53.

For LTS, you can use django-db-geventpool 3.2.x branch, see https://github.com/jneight/django-db-geventpool/releases/tag/v3.2.4
