### ISSUE TITLE
What if `CONN_MAX_AGE` > 0?

### ISSUE THREAD

**Issue by mindflayer** [jneight/django-db-geventpool#60]
The question is: what if I set a `CONN_MAX_AGE` greater than `0`, would it be respected?
Would Django close that connection after that certain amount of time?
I am asking this because I want my system to be able to get advantage of all the connections allowed by the pool limit, but I also want this number to go down when all these connections are not needed anymore.

**Comment by jneight** [comment]
In that case, django will call `close()` and the connection will return to the pool if it is still usable.

**Comment by mindflayer** [comment]
Thanks for the answer!
