### ISSUE TITLE
Patch psycopg when using celery

### ISSUE THREAD

**Issue by davyneven** [jneight/django-db-geventpool#61]
I'm having both a django web process and a celery worker running. 
My procfile looks like:
`web: gunicorn project.wsgi --workers 3 -k gevent --worker-connections 100 --config gunicorn_config.py`
`worker: celery -A project worker --pool=gevent --concurrency=500`
The web process is using gunicorn, which patches psycopg as explained in the readme. However, as celery is also using gevent, do I need to patch this as well?

Thanks!

**Comment by jneight** [comment]
Hi!

Yes, you should add the patch code when using celery, your celery.py should be a good place.

Also, is recommended to use @close_conection decorator, see https://github.com/jneight/django-db-geventpool#using-orm-when-not-serving-requests

**Comment by davyneven** [comment]
Ok, thanks! I have indeed patched psycogreen in the celery.py file, using the celeryd_init signal so that each worker is patched at startup. It seems to work fine. 

```
@celeryd_init.connect
def patch_psycogreen(**kwargs):
    from psycogreen.gevent import patch_psycopg
    patch_psycopg()
```
