### ISSUE TITLE
support for psycopg3?

### ISSUE THREAD

**Issue by engAmirEng** [jneight/django-db-geventpool#76]
Hi and thanks for your hard work.
we steel want the battle tested synchronous django and it is worthless at least for me without gevent and now we need support for psycopg3

**Comment by johnnymetz** [comment]
+1

**Comment by jneight** [comment]
Hi, psycopg3 not longer needs psycogreen, so I think I will release a last version supporting django versions prior to 4.2 and then clean and update code for the LTS 4.2 version

**Comment by engAmirEng** [comment]
> Hi, psycopg3 not longer needs psycogreen, so I think I will release a last version supporting django versions prior to 4.2 and then clean and update code for the LTS 4.2 version

Hey, How come?

**Comment by jneight** [comment]
Hi!, I just released a new version with support for psycopg3, just edit your setting for ENGINE to `django_db_geventpool.backends.postgresql_psycopg3` in DATABASE_SETTINGS and it should work as always.

**Comment by augustolima** [comment]
Hey, @jneight. I've updated to 4.0.3 but I'm receiving an error:
```Exception has occurred: ImproperlyConfigured
'django_db_geventpool.backends.postgresql_psycopg3' isn't an available database backend or couldn't be imported. Check the above exception. To use one of the built-in backends```

Here's my requirements.txt:
psycopg[binary]
django-db-geventpool==4.0.3

When opening the lib on `venv`, there's no folder for `psycopg3`.
